nginx.conf
nuxt.config.ts

Le déploiement sur scalingo se termine en succès, mais on a une 404 lorsque l'on tente d'accéder à la ressource.
Modifier le chemin utilisé par nginx pour servir les ressources.
-
Aller sur l'intégration : https://pix-tutos-integration.osc-fr1.scalingo.io/ et vérifier qu'on a le même rendu qu'en local.

[BUGFIX] Modification du répertoire de build (PIX-5045).

---

content/la-certification.json
content/les-tutos.json
nuxt.config.js
package-lock.json
package.json
pages/_slug.vue
pages/index.vue

Nous souhaitons pouvoir lire les informations des différentes pages constituant les tutos vidéo à partir de fichier JSON
Ajout du module `NuxtContent`
N/A
Sur la RA, aller sur `/la-certification` et vérifier que le contenu affiché correspond au contenu du fichier JSON du même nom.

[TECH] Ajout du module Nuxt Content (PIX-5032).

---

package-lock.json
package.json
scripts/jira/comment-with-review-app-url.js
scripts/signal_deploy_to_pr.sh

Actuellement, il peut être compliqué de retrouver le lien de la RA
Ajouter les commentaires comme sur les autres repos Pix en copiant et adaptant les scripts existants.
Lié à la PR : https://github.com/1024pix/pix-review-router/pull/6

[TECH] Ajouter les commentaires avec le lien de la Review App (PIX-5134). 

---

.circleci/config.yml
.eslintrc.js
content/la-certification.json
content/les-tutos.json
jest.config.js
package-lock.json
package.json
tests/verify-content.test.js

Il n'y avait aucune validation de contenu.
Ajout de tests pour valider le format du fichier, la présence des champs obligatoire et la validation de son contenu.
RAS
Vérifier que la CI passe bien.

[FEATURE] Ajout de tests pour valider le contenu (PIX-5512)

---

content/utiliser-les-reseaux-sociaux-comme-outils-de-veille-informationnelle.json

Nouveau tuto (8) : Utiliser les réseaux sociaux comme outils de veille informationnelle

---

content/identifier-des-sources-de-veille-incontournables.json

Nouveau tuto (9) : Identifier des sources de veille incontournables

---

content/les-acteurs-de-la-formation-en-ligne-des-enseignants.json

Nouveau tuto (10) : Les acteurs de la formation en ligne des enseignants

---

content/les-donnees-a-caractere-personnel-en-milieu-scolaire.json

Nouveau tuto (11) : Les données à caractère personnel en milieu scolaire

---

content/le-rgpd-en-milieu-scolaire.json

Nouveau tuto (12) : Le RGPD en milieu scolaire

---

content/le-cyberharcelement.json

Nouveau tuto (14) : Le cyberharcèlement

---

content/le-modele-samr-pour-integrer-le-numerique-dans-la-pedagogie.json

Nouveau tuto (15) : Le modèle SAMR pour intégrer le numérique dans la pédagogie

---

content/suivre-les-avancees-de-la-recherche-sur-le-numerique-educatif.json

Nouveau tuto (16) : Suivre les avancées de la recherche sur le numérique éducatif

---

content/utiliser-une-illustration-en-licence-libre.json

Nouveau tuto (19) : Utiliser une illustration en licence libre

---

content/le-droit-d-auteur-des-eleves.json

Nouveau tuto (21) : Le droit d'auteur des élèves

---

content/methodes-et-outils-pour-concevoir-une-capsule-video.json

Nouveau tuto (23) : Méthodes et outils pour concevoir une capsule vidéo

---

content/utiliser-des-capsules-video-en-classe.json

Nouveau tuto (25) : Utiliser des capsules vidéo en classe

---

content/la-classe-inversee.json

Nouveau tuto (27) : La classe inversée

---

content/les-fonctionnalites-de-retroaction-des-outils-de-quiz-en-ligne.json

Nouveau tuto (32) : Les fonctionnalités de rétroaction des outils de quiz en ligne

---

content/reperer-une-copie-ayant-eu-recours-au-plagiat.json

Nouveau tuto (34) : Repérer une copie ayant eu recours au plagiat

---

content/comprendre-les-creative-commons-pour-une-utilisation-pedagogique.json

Nouveau tuto (20) : Comprendre les Creative Commons pour une utilisation pédagogique

---

content/sites-ressources-pour-l-ecole-inclusive.json

Nouveau tuto (35) : Sites ressources pour l'école inclusive

---

content/utiliser-les-outils-de-quiz-en-ligne-pour-diversifier-son-evaluation.json

Nouveau tuto (31) : Utiliser les outils de quiz en ligne pour diversifier son évaluation

---

content/outils-pour-rendre-un-document-accessible.json

Nouveau tuto (36) : Outils pour rendre un document accessible

---

content/les-systemes-robotises-de-telepresence.json

Le dernier de la première vague ! :)

Nouveau tuto (38) : Les systèmes robotisés de téléprésence

---

pages/edu/index.vue

Retour de Romain : libellés à revoir.
Changement de libellés.
RAS.
Voir la RA.

[FEATURE] Amélioration libellés page d'accueil Pix+Édu

---

content/edu/agir-face-au-cyberharcelement.json
content/edu/cadre-et-acteurs-du-rgpd-en-milieu-scolaire.json
content/edu/comprendre-comment-differencier-grace-au-numerique.json
content/edu/le-cadre-de-reference-des-competences-numeriques.json
content/edu/le-cahier-de-texte-numerique.json
content/edu/le-modele-tpack-pour-integrer-le-numerique-dans-la-pedagogie.json
content/edu/les-erun-acteurs-du-numerique-educatif.json
content/edu/les-travaux-academiques-mutualises.json
content/edu/partager-et-diffuser-sa-veille-informationnelle.json
content/edu/resoudre-des-problemes-simples-lies-aux-outils-numeriques.json
content/edu/trouver-et-proposer-des-ressources-pour-le-site-prim-a-bord.json

Ajout des descriptions courtes pour les nouveaux tutoriels Canopé

---

.circleci/config.yml
.gitignore
package-lock.json
package.json
playwright.config.ts
tests/e2e/content.spec.ts.js
tests/unit/services/customizing-embed-video.test.js
tests/unit/verify-edu-content.test.js

Actuellement, nous n'avons pas de test confirmant le bon fonctionnement de l'application en globalité, ce qui a provoqué une regression par la PR #103 
Mettre en place des tests avec playwright.
Voir la CI.
En local :
```
npm ci
npm run test:e2e
```
Pour limiter à un seul navigateur :
`npx playwright test --project chromium`

[TECH] Ajouter des tests de non régressions

---

content/edu/comprendre-comment-differencier-grace-au-numerique.json
content/edu/partager-et-diffuser-sa-veille-informationnelle.json

Correctifs coquilles (titre / domaine)

---

content/edu/mettre-en-place-une-strategie-de-veille.json

Création d'une nouvelle page pour un nouveau tuto

Création d'une page pour un nouveau tuto

---

layouts/edu.vue
layouts/simple.vue
pages/edu/[slug].vue
pages/edu/index.vue
pages/index.vue

Nous utilisons encore la syntaxe de Vue2 et Nuxt2
Utiliser les nouvelles syntaxes.
- Naviguer sur l'application et vérifier le bon fonctionnement

[TECH] Utiliser les nouveautés de Nuxt3 et de Vue3 (PIX-8163).

---

content/edu/accessibilite-des-apprentissages-et-numerique.md
content/edu/le-developpement-des-competences-numeriques-des-eleves.md
content/edu/le-numerique-pour-developper-les-competences-psychosociales-des-eleves.md
content/edu/le-numerique-pour-renforcer-la-relation-ecole-familles.md
content/edu/le-travail-en-equipe-un-levier-pour-enseigner-avec-le-numerique.md
content/edu/les-apports-de-la-recherche-pour-utiliser-le-numerique-avec-discernement.md
content/edu/les-outils-numeriques-pour-repenser-ses-pratiques-pedagogiques.md
content/edu/pratiques-numeriques-des-eleves-les-comprendre-pour-mieux-les-accompagner.md

Création pages tutos.pix pour webinaires (+9 pages)

---

content/edu/accompagner-les-eleves-a-la-maitrise-de-leur-identite-numerique.md
content/edu/ameliorer-la-cybersecurite-de-ses-outils-numeriques.md

Une autre PR à venir pour finaliser l'ajout de transcription

Tuto Pix +Edu Mise à jour de 2 transcription

---

pages/mednum/index.vue
tests/e2e/mednum/content.spec.ts

La MedNum n'a pas encore de description sur sa page d'accueil.
L'ajouter avec le contenu de Romain.
RAS
Non régression visuelle

[FEATURE] Ajouter la description sur la page d'accueil de la mednum (PIX-9305)

---

content/edu/les-donnees-a-caractere-personnel-en-milieu-scolaire.md

Correction coquille sur tuto +Edu (les-donnees-a-caractere-personnel-en-milieu-scolaire.md)

---

content/sixieme/identifier-des-situations-d-arnaque-par-manipulation-psychologique.md

Correction page tuto identifier-des-situations-d-arnaque-par-manipulation-psychologique

---

content/sixieme/connaitre-et-utiliser-la-capacite-du-gps-et-d-une-adresse-ip-a-geolocaliser-un-appareil.md
content/sixieme/connaitre-les-notions-de-donnees-a-caractere-personnel-de-recoupement-et-d-anonymisation.md
content/sixieme/connaitre-les-recommandations-pour-le-choix-d-un-mot-de-passe-robuste.md
content/sixieme/identifier-des-situations-d-arnaque-par-manipulation-psychologique.md
content/sixieme/maitriser-l-acces-a-ses-donnees-lors-de-l-installation-d-une-application.md

Corrections titre vidéo

---

content/edu/le-developpement-des-competences-numeriques-des-eleves.md

Absence de transcriptions et de lien de téléchargement sur certains pages de https://tutos.pix.fr/edu (webinaires et extraits de webinaires)
Ajouter
RAS
Allez voir les pages concernées : 
- https://pix-tutos-review-pr332.osc-fr1.scalingo.io/edu/le-developpement-des-competences-numeriques-des-eleves

[FEATURE] Ajout des transcriptions et des liens de téléchargement des webinaires

---

.github/workflows/release.yaml

Voir https://github.com/1024pix/pix-tutos/actions/runs/10629712040/job/29467121142

[TECH] Ajoute un checkout manquant dans l'action de release
