1024pix/pix-tutos

.github/workflows/auto-merge.yml
Actuellement, nous ne pouvons merger que manuellement à partir du bouton de github. Nous souhaitons pouvoir le faire grâce au label Ready to merge, de la même manière que sur les autres repos de 1024pix.
Mettre en place la github action auto-merge
N/A
Merger cette PR avec le label 'Ready to merge'
=> [TECH] Ajout de la github action automerge (PIX-5029).

.eslintrc.js, .gitignore, .prettierrc.json, TUTOS.js, nuxt.config.js, package-lock.json, package.json, pages/_slug.vue, pages/index.vue
Il n'y pas de formatter et de linter installé sur le projet
Les installer
On utilise la même configuration que sur pix-site
Checkout la branche, faire des modifications et lancer la commande `npm run lint:fix`. Constater que le code est formaté
=> [TECH]: Ajouter Prettier et Eslint (PIX-5073).

.gitignore, README.md, docker-compose.yml, nginx.conf, servers.conf.erb
Actuellement, nous ne pouvons pas nous rendre directement sur un tutoriel car la redirection nginx ne fonctionne pas correctement. 
- Ajout d'un serveur écoutant sur le PORT passé en variable d'environnement
- Ajout de l'option : `port_in_redirect off;` qui permet le bon fonctionnement de la redirection.
- Ajout des access_log dans le bon format pour Datadog
- Se rendre sur : https://pix-tutos-review-pr13.osc-fr1.scalingo.io/la-certification
=> [BUGFIX] Accéder à un tutoriel sans devoir passer par la page d'accueil. 

nuxt.config.js, services/is-seo-indexing-enabled.js
Actuellement, l'indexation est activé sur tous les environnements. Cependant nous souhaitons avoir uniquement la production d'indexé et uniquement quand on le souhaitera. 
Ajouter l'ajout d'une balise meta robot noindex conditionné par une variable d'environnement.
=> [TECH] Pouvoir activer l'indexation grâce à une variable d'environnement (PIX-5142).

layouts/error.vue, layouts/simple.vue, nuxt.config.js, servers.conf.erb
Nous utilisons à l'heure actuelle la page d'erreur Nginx en cas de 404, et voudrions utiliser une page custom à la place.
Modification de la config Nuxt pour renvoyer la page `404.html` en cas d'erreur.
Ajout d'une page `error.vue` dans le dossier `layout` de Nuxt.
Garde t-on la redirection vers `pix.fr` comme sur `Pix-site` sachant que celle-ci peut déjà se faire via la barre de navigation ?
Le style est très "brut", si vous avez des pistes d'amélioration, je suis tout ouïe.
Sur la RA, vérifier que la page rendue est bien la page 404 nouvellement créée en cas d'URL invalide.
=> [FEATURE] Ajout d'une page 404 custom (PIX-5074).

components/PixTutorial.vue, layouts/default.vue, layouts/error.vue, layouts/simple.vue, nuxt.config.js, pages/_slug.vue, services/is-seo-indexing-enabled.js
La vidéo était parfois plus grande que le viewport.
Réduire la largeur du container et prévoir le cas où le viewport est vraiment petit pour avoir une taille de vidéo relative.
On s'est aussi servi de la PR pour lint le code
Ouvrir une page tuto et réduire la hauteur et/ou la largeur de l'écran et vérifier que la vidéo ne déborde pas.
=> [BUGFIX] La hauteur de la vidéo d'un tutoriel ne doit pas être trop grande

.circleci/config.yml
On ne lançait pas le linter dans le CI.
L'ajouter
On s'est basé sur la config de pix-site.
Pusher un commit mal formaté de test et voir que la CI ne passe pas.
=> [TECH] Ajout du linter dans le CI

components/PixHeader.vue, layouts/default.vue
Il n'y a pour le moment pas de lien pour aller vers Pix depuis pix-tutos.
Ajouter des liens vers la page de connexion et d'inscription si une query string commençant par `?c` n'est pas passée.
On pourra ajouter cette query string dynamiquement côté app.pix.fr.
`?c` validé avec Manux.
1. Accéder à la RA
2. Vérifier que les boutons d'accès à la page d'inscription et de connexion sont bien présents
Ex: https://pix-tutos-review-pr16.osc-fr1.scalingo.io/les-tutos
3. Ajouter la query string `?connecte` sur n'importe quelle page et vérifier que ces liens ont disparu.
Ex: https://pix-tutos-review-pr16.osc-fr1.scalingo.io/la-certification?c
=> [FEATURE] Ajoute les boutons de connection et d'inscription si absence de query string `?c` (PIX-5119)

config/environment.js, nuxt.config.js, static/scripts/start-matomo-event.js
Actuellement, nous n'avons pas l'audience de ce site
Ajouter Matomo Tag Manager comme sur les autres sites
La variable a été ajouté sur l'environnement de production
=> [FEATURE] Ajouter Matomo Tag Manager comme suivie d'audience (PIX-5328).

scripts/jira/comment-with-review-app-url.js
Sur Jira, le commentaire généré ne fait pas de nouveau paragraphe après le lien de la RA dans le commentaire de création de PR.
Comme sur les autres applis, utiliser 2 sauts de ligne. Exemple : https://github.com/1024pix/pix/blob/9d3248e64807dffe1f0905e6d42be5232c2107c3/scripts/jira/comment-with-review-app-url.js#L60
RAS
Voir le résultat avec cette PR.
=> [TECH] Ajoute un saut de ligne dans le commentaire Jira (PIX-5243)

nuxt.config.js
Actuellement, l'ajout du script de Matomo TM, ne fonctionne pas car la valeur `script` n'est pas défini dans `nuxtConfig`.
Ajouter cette valeur avec un tableau vide
=> [BUGFIX] Ajouter le script Matomo Tag Manager

nuxt.config.js, pages/index.vue
On ne sait pas que le tuto appartient à Pix+Édu. Remonté par Romain.
Ajouter le contexte Pix+Édu dans le titre de la page.
Est-ce que ça sera bien utilisé pour l'indexation Google ?
Vérifier le title de la page.
=> [FEATURE] Ajouter le contexte Pix+Édu dans le titre de la page d'un tuto

.babelrc, assets/scss/globals.scss, components/PixTutorial.vue, components/PixTypography.vue, pages/edu/_slug.vue, pages/edu/index.vue, pages/index.vue, services/get-areas.js, tests/verify-edu-content.test.js
Après l’ajout des infos de domaine (champ area), on peut concevoir une plus jolie page d'accueil de Pix+Édu.
Intégrer la maquette des sous pages de Pix+Édu : la page d'accueil et un lien pour y retourner depuis un tuto. On se laisse quelques libertés sur le design, sur les blocs tutos l'info "vidéo" et "durée" ne sont pas nécessaires dans ce MVP.
On a essayé de faire attention à la typo en reprenant ce qu'on trouve dans les design tokens typography mais on est pas très convaincus du résultat. On a créé un composant `PixTypography` pour mettre en commun les styles et la sémantique des pages.
On vérifie maintenant dans la CI que l'`area` sélectionnée possède bien une traduction de notre côté.
Checker la RA.
=> [FEATURE] Intégration page d'accueil Pix+Édu (PIX-5631)

components/PixTutorial.vue, pages/edu/_slug.vue, services/customizing-embed-video.js, tests/services/customizing-embed-video.test.js
Le lecteur vidéo affiche des informations qu'on ne souhaite pas comme : 
- le bouton "PeerTube"
- le titre de la vidéo
- le warning comme quoi l'IP est stockée
Ajouter des queryParams à l'url pour customiser l'url.
- Aller sur un tuto et constater qu'il n'y plus les éléments
=> [FEATURE] Customiser le lecteur vidéo (PIX-5659).

pages/edu/_slug.vue, pages/edu/index.vue
Le lien de retour à la liste des tutos Pix+Édu est incohérent dans le contexte de présentation des tutos.
Supprimer le lien.
Aussi correction d'un libellé.
Vérifier sur la RA que le lien n'apparaît plus et que le libellé est à jour.
=> [FEATURE] Ajustements lien retour à la liste + libellé (PIX-5676)

pages/edu/index.vue
Les domaines ne sont pas affichés dans l'ordre alphabétique
Lors de la migration en Nuxt Content v2, nous n'avons pas respecté[ le nouveau format de tri](https://content.nuxtjs.org/api/composables/query-content/#sortoptions) 
- Se rendre sur /edu 
- Vérifier que les domaines sont affichés dans l'ordre alphabétique
=> [BUGFIX] Rétablir l'ordre des domaines (PIX-8149).

nuxt.config.ts
Dans les transcripts, on se retrouve avec des liens d’ancres sur les titres du markdown. Ils portent à confusion, on souhaite que ce ne soit plus des liens. (L’`id` peut rester)
Configurer Nuxt Content pour ne plus ajouter les liens dans les ancres.
RAS
Vérifier sur la RA que le premier tuto n'a pas de lien autour de l'ancre.
=> [BUGFIX] Supprimer le lien d'ancrage des transcripts (PIX-8156)

components/PixTutorial.vue
L'espace entre le bouton "telechager" et la video et le text sont pas equilibres
Ajouter plus d'espace
RAS
Aller sur un tutoriel et verifier les espaces
=> [BUGFIX] Resserrer le bouton de téléchargement et le bloc vidéo (PIX-8155)

assets/scss/globals.scss, components/PixButton.vue, components/PixTutorial.vue, layouts/edu.vue
Actuellement, il n'y a pas de bouton à disposition pour télécharger le pdf du transcript.
Styliser l'affichage du transcript pour l'impression et ajouter un bouton de téléchargement (bouton d'impression).
- Aller sur un tutoriel 
- Cliquer sur le bouton "Télécharger la retranscription"
=> [FEATURE] Ajouter un bouton de téléchargement du transcript (PIX-8151).

layouts/edu.vue
A l'impression, on a pas le logo pix
Ajouter le logo sur l'impression pix quand les utilisateurs vont telecharger la transcription
Pas des remarques
Aller sur pix.tuto
cliquer sur un tuto
cliquer sur le bouton "telecharger la transcription"
Verifier que le logo pix et bien ajouter sur la haute gauche de l'impression
=> [FEATURE] A l'impression, ajouter le logo de Pix

nuxt.config.ts
Lors de la montée de version vers Nuxt 3 #141 la configuration de Matomo s'est perdue
Rajouter la configuration
- Ajouter la varible d'environnement MATOMO_CONTAINER sur la RA
- Rédeployer 
- Constater le bon téléchargement du container dans l'onglet network
=> [BUGFIX] Rétablir Matomo

pages/edu/index.vue
Actuellement, l'ordre des domaines n'est pas correct
Il faut d'abord trier par titre, puis ensuite par domaine, si nous faisons l'inverse le trie par titre l'emporte
- Se rendre sur la page /edu
=> [BUGFIX] Corriger l'ordre des domaines sur /edu 

services/get-areas.ts
Il est restrictif d'avoir uniquement le choix entre les 5 domaines de Pix, alors que certains webinaires sont transverses.
Ajouter une section `Webinaire`
=> [FEATURE] Permettre d'avoir `Webinaires` comme domaine de tutoriel (PIX-8618)

assets/scss/globals.scss, components/PixVideoPlayer.vue
Le clic droit est interdit sur les vidéos Plyr.
L'activer pour permettre l'utilisation fonctionnalités natives des navigateurs.
La doc du paramètre utilisé :
> Disable right click menu on video to help as very primitive obfuscation to prevent downloads of content.
Accéder à `<RA>/mednum/interagir-avec-une-visualisation`
=> [FEATURE] Permettre le clic droit sur les vidéos Plyr (PIX-9157)

assets/translation/player_fr.js, components/PixVideoPlayer.vue
Par défaut le player vidéo plyr utilisé pour MedNum est en anglais et ne possède pas de traduction française intégrée.
Intégrer à la main la traduction française (à compléter avec Anaïs)
> ⚠️ Pour les devs, l'endroit où j'ai rangé le fichier de trad est évidemment à challenger :)
[Discussion sur le sujet dans le repo de plyr](https://github.com/sampotts/plyr/issues/1261)
[Commit sur le repo de plyr avec les locales anglais](https://github.com/filips123/plyr/commit/ed4af258de7dc7ecc5791ade58d28f4f1e55399c)
Ouvrir par exemple [cette page](https://tutos.integration.pix.fr/mednum/interagir-avec-une-visualisation) et vérifier les traductions dans l'option de la vidéo (engrenage en bas à droite du player)
=> [FEATURE] Ajout de la traduction française pour le player vidéo de MedNum (PIX-9226)

components/PixPdf.vue
Dans les tutos PDF de la MedNum, il faut modifier le CTA "Télécharger le pdf" en "Ouvrir le PDF".
Modification en dur du texte du bouton
> _nope_
Checker visuellement sur `mednum/icone-de-la-messagerie` par exemple.
=> [BUGFIX] Page MedNum - modifier le label du CTA pour les PDF (PIX-9300)

pages/mednum/index.vue
Une coquille s'est glissée dans le texte de la description.
Petite correction en dur
> _nope_
Correction visible ici `/mednum`
=> [BUGFIX] Coquille à corriger dans la description de l'accueil de Mednum (PIX-9305)

assets/scss/globals.scss, layouts/mednum.vue
Le lecteur vidéo de la MedNum est affiché lors de l'impression, et donc du clic sur le bouton "Télécharger la transcription".
Le supprimer.
Ajouter la classe `.tuto__video` sur `PixVideoPlayer` n'est pas suffisant car Plyr ajoute des éléments qui prennent de l'espace autour de la balise video. D'où l'usage de la classe `.plyr` directement.
Vérifier que le lecteur est caché à l'impression, et visible à l'usage habituel.
=> [BUGFIX] Cache le lecteur vidéo de la MedNum dans les styles d'impression (PIX-9460)

.eslintrc.js, config/environment.js, package-lock.json, package.json
La config ESLint génère un conflit entre `nuxt` et `antfu`.
Suivre la recommandation de cette réponse [StackOverflow](https://stackoverflow.com/questions/76803864/eslint-with-nuxt3-auto-import) en n'utilisant plus que la dernière version de la config [`antfu`](https://github.com/antfu/eslint-config).
RAS
Vérifier que les vars d'env Matomo sont bien lues.
=> [TECH] Corriger la config ESLint (PIX-9462)

package.json, pages/mednum/[slug].vue
Le lecteur vidéo en plein écran n'est pas centré sur la page en mobile et déborde donc il est impossible d'utiliser les commandes pour mettre en pause ou quitter le mode plein écran par exemple.
Le recentrer.
J'ai ajouté un script npm pour lancer le mode dev sur son réseau local, pour pouvoir y accéder depuis un smartphone par exemple.
Accéder à l'intégration sur un mobile et comparer le résultat avec cette RA.
=> [BUGFIX] Centrer le lecteur vidéo MedNum en plein écran sur mobile (PIX-9469)

components/PixVideoPlayer.vue, content/sixieme/comment-reconnaitre-des-situations-de-cyberharcelement-et-comment-y-faire-face.md, layouts/sixieme.vue, pages/index.vue, pages/sixieme/[slug].vue, pages/sixieme/index.vue, tests/e2e/sixieme/content.spec.ts, tests/unit/verify-sixieme-content.test.js
On doit donner accès à des vidéos pour les sixièmes. Il faut qu'ils puissent y accéder jeudi matin de cette semaine.
Ajouter les pages nécessaires au bon fonctionnement de Pix Tutos. Elles apparaissent maintenant dans `/sixieme`.
J'ai initié un layout `sixieme` qui est un copié collé de celui de la `mednum`. Peut-être faudrait-il faire un layout plus générique ?
Vérifier qu'on peut accéder à une capsule vidéo dans `/sixieme`.
=> [FEATURE] Ajouter des tutos vidéos pour les sixièmes (PIX-9958)

components/PixPdf.vue, pages/edu/[slug].vue, pages/mednum/[slug].vue
Le nom du bouton d'action "Télécharger la transcription" porte à confusion.
Le renommer pour clarifier son intention.
Également une mini reprise technique sur le bouton d'ouverture du PDF.
RAS
Vérifier que :
- les boutons d'impression de transcription fonctionnent toujours (+Edu et mednum).
- le bouton pour ouvrir le PDF doit toujours fonctionner.
=> [FEATURE] Renommer des boutons d'action (PIX-9950) (PIX-9166)

components/PixVideoPlayer.vue, docker-compose.yml
Plyr par defaut appel au CDN (cloudfare) pour telecharger les icons.
Retirer l'appel au CDN et loader les icon de `node_modules`
Aller [ici](https://pix-tutos-review-pr267.osc-fr1.scalingo.io/mednum/interagir-avec-une-visualisation) et verifier qu'il n y a pas un appel vers le CDN
=> [TECH] Retirer l'appel au CDN de Plyr (PIX-10561)

.circleci/config.yml
Node.js ne se met pas à jour partout au même moment entre : 
- Circle CI
- .npmrc
- package.json
De [la même manière qu'ailleurs](https://github.com/1024pix/pix-ui/blob/053f1d16566aa99815e4911bc65112aee4336a62/.circleci/config.yml#L9C20-L10C56), faire en sorte que les montées de version de Node soit groupées.
RAS
🤷
=> [TECH] Regrouper les montées de version Node

.github/workflows/compressed-size.yaml
Pour suivre les évolutions de taille de bundle, on peut utiliser [compressed-size-action](https://github.com/preactjs/compressed-size-action). Essayer :)
=> [TECH] Ajoute un calculateur de taille de bundle

content/edu/accompagner-les-eleves-a-la-maitrise-de-leur-identite-numerique.md, content/edu/connaitre-des-supports-educatifs-ludiques-numeriques.md, content/edu/eduquer-aux-donnees-pour-developper-des-communs.md, content/edu/le-bien-etre-numerique.md, content/edu/les-acteurs-institutionnels-du-numerique-educatif-dans-le-1er-degre.md, content/edu/les-banques-de-ressources-pedagogiques-en-ligne.md, content/edu/les-femmes-dans-les-metiers-du-numerique.md, content/edu/les-groupes-thematiques-numeriques-gtnum.md, content/edu/les-impacts-ecologiques-du-numerique.md, content/edu/les-modeles-economiques-du-numerique.md, content/edu/mettre-a-disposition-et-partager-des-ressources-a-des-pairs-2nd-degre.md, content/edu/outils-pour-differencier-grace-au-numerique.md, content/edu/realite-augmentee-et-realite-virtuelle-au-service-des-apprentissages.md, content/edu/recherche-sur-internet-bulles-de-filtres-et-desinformation.md, content/edu/utiliser-et-creer-des-supports-educatifs-ludiques-numeriques.md, tests/unit/verify-edu-content.test.js
Il manquait des liens de téléchargement sur une 15aine de tutoriels +Edu by Canopé
Ajout
Absence de lien détectée en cherchant
`videoDownloadHref: ---`
Sur les pages modifiées, voir si le bouton téléchargement est bien présent et mène au bout lien
=> [FEATURE] Ajout de lien de téléchargement manquant

.github/workflows/auto-merge.yml
Aujourd’hui la plupart des projets Pix utilisent le tag GitHub “🚀 Ready to merge” qui déclenche le bot “Jean Pierre Pernault” AKA pix-auto-merge qui s’assure que la PR soit à jour. Si elle ne l’est pas, Jean Pierre lance un rebase sans fast-forward et relance la CI avant de merger la PR.
Expérimenter l'usage des fonctionnalités natives de GitHub.
Déclencher Jean Pierre et voir le résultat.
=> [TECH] Remplacer Jean Pierre par le bouton de merge natif

.github/workflows/auto-merge.yml
Reverts 1024pix/pix-tutos#366
Il semblerait que le squash & merge ne fonctionne pas pour générer une release auto. Voir https://github.com/1024pix/conventional-changelog-pix/pull/46
=> Revert "[TECH] Remplacer Jean Pierre par le bouton de merge natif"

CHANGELOG.md
Depuis le 30 septembre nous n’avons plus déploiements en prod auto depuis pix-tutos.
Remettre en place ce déploiement continu en réactivant Jean Pierre.
RAS
N/A
=> [TECH] Remise au propre du CHANGELOG (PIX-15203)
